apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netshoot
  template:
    metadata:
      labels:
        app: netshoot
    spec:
      containers:
      - args:
        - -c
        # - while true; do ping localhost; sleep 3660;done
        - sleep 3660
        command:
        - /bin/bash
        image: nicolaka/netshoot:v0.16

        name: netshoot
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: podtest
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
  name: podtest